### ISSUE TITLE
添加版本号显示

### ISSUE THREAD

**Issue by undefined-hestudio** [hestudio-community/bing-wallpaper-get#2]
在程序启动时显示当前版本号并联网检查版本更新，如果有更新在日志提示用户更新。

**Comment by yakefu-pa** [comment]
VERSION="1.0.0"

**Comment by yakefu-pa** [comment]
VERSION="1.0.0"

**Comment by yakefu-pa** [comment]
VERSION="2.0.0"

**Comment by undefined-hestudio** [comment]
> VERSION="2.0.0"

@yakefu-pa 

应该把他加到代码里面输出，而不是写在issue里

并且，我当前最新的版本可以在标签里查询
